[package]
name = "hello-rocket"
version = "0.1.0"
authors = ["bvincent1 <benjc.vincent@gmail.com>"]

[dependencies]
rocket = "0.2.6"
rocket_codegen = "0.2.6"
rusoto_core = {version = "0.25.0"}
rusoto_dynamodb = {version = "0.25.0"}
